import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    appName: 'TeeraConnect',
    tagline: 'Coastal Weather & Fisher Community',
    home: 'Home',
    forecast: 'Forecast',
    map: 'Map',
    community: 'Community',
    sos: 'SOS Help',
    admin: 'Admin',
    lastUpdated: 'Last updated',
    simulatedData: 'Simulated Data',
    realTimeData: 'Real-time API Data',
    refresh: 'Refresh',
    selectLocation: 'Select Harbor/Location',
    safetyStatus: 'Safety Status',
    safeToGo: 'Safe to go out',
    cautionGo: 'Caution - check conditions',
    dangerGo: 'Do not go out - Danger',
    wind: 'Wind Speed',
    windDir: 'Wind Direction',
    waves: 'Wave Height',
    tides: 'Tide Schedule',
    highTide: 'High Tide',
    lowTide: 'Low Tide',
    sunrise: 'Sunrise',
    sunset: 'Sunset',
    humidity: 'Humidity',
    rainChance: 'Rain Chance',
    knots: 'knots',
    meters: 'm',
    tempRange: 'Temp Range',
    weatherTitle: 'Today\'s Weather',
    forecastTitle: '5-7 Day Sea Forecast',
    mapTitle: 'Fishing Zones Map',
    zonesLegend: 'Legend: Green = Safe, Orange = Caution, Red = Danger',
    catchReports: 'Catch Logs',
    marketPrices: 'Market Board',
    postCatch: 'Report Catch',
    postPrice: 'Update Price',
    fishType: 'Fish Type',
    quantity: 'Quantity (kg)',
    location: 'Harbor Location',
    postBtn: 'Submit',
    pricePerKg: 'Price per kg',
    postedBy: 'Posted by',
    activeAlerts: 'Active Advisories',
    emergencyContacts: 'Coastal SOS Contacts',
    shareLocation: 'Share Location via WhatsApp',
    sosTitle: 'EMERGENCY SOS',
    sosInstructions: 'Tap below to share your exact GPS coordinates with family & Coast Guard.',
    coordinates: 'Your Coordinates',
    fetchingCoords: 'Getting GPS location...',
    gpsError: 'GPS location unavailable. Please share last known harbor.',
    adminTitle: 'Fisheries Officer Console',
    adminPassword: 'Enter Admin Password',
    adminSubmit: 'Log In',
    adminLogout: 'Log Out',
    postAlertTitle: 'Create New Marine Advisory',
    alertTitle: 'Advisory Title',
    alertBody: 'Alert Details',
    alertSeverity: 'Severity Level',
    alertExpiry: 'Expires in (Hours)',
    info: 'Info Advisory',
    warning: 'Caution Warning',
    danger: 'Danger Storm Alert',
    moderateCatches: 'Moderate Catch Reports',
    priceTrend: 'Price per KG Board',
    addPriceSuccess: 'Market price updated!',
    addCatchSuccess: 'Catch report shared!',
    addAlertSuccess: 'Advisory posted!',
    deleteBtn: 'Delete',
    loading: 'Loading...',
    fisherRole: 'Fisherman',
    buyerRole: 'Seafood Buyer',
    adminRole: 'Fisheries Admin',
    buyerHub: 'Buyer Hub',
    dealsInbox: 'Deals Inbox',
    priceTrends: 'Price Trends',
    fisherProfile: 'Fisher Profile',
    boatType: 'Boat Type',
    companyName: 'Company Name',
    requestDeal: 'Offer Deal',
    contactFisher: 'Contact Fisher',
    verified: 'Verified',
    pendingDeals: 'Pending Deals',
    acceptedDeals: 'Accepted Deals',
    declinedDeals: 'Declined Deals'
  },
  kn: {
    appName: 'ತೀರ ಕನೆಕ್ಟ್ (TeeraConnect)',
    tagline: 'ಕರಾವಳಿ ಹವಾಮಾನ ಮತ್ತು ಮೀನುಗಾರರ ಸಮುದಾಯ',
    home: 'ಮುಖಪುಟ',
    forecast: 'ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    map: 'ನಕ್ಷೆ',
    community: 'ಸಮುದಾಯ',
    sos: 'ತುರ್ತು ಸಹಾಯ',
    admin: 'ಅಡ್ಮಿನ್',
    lastUpdated: 'ಕೊನೆಯದಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ',
    simulatedData: 'ಅನುಕರಣೆಯ ಡೇಟಾ (ಸಿಮ್ಯುಲೇಟೆಡ್)',
    realTimeData: 'ನೈಜ ಸಮಯದ ಡೇಟಾ',
    refresh: 'ನವೀಕರಿಸಿ',
    selectLocation: 'ಬಂದರು/ಸ್ಥಳವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    safetyStatus: 'ಸುರಕ್ಷತೆಯ ಸ್ಥಿತಿ',
    safeToGo: 'ಸಮುದ್ರಕ್ಕೆ ಹೋಗಲು ಸುರಕ್ಷಿತವಾಗಿದೆ',
    cautionGo: 'ಎಚ್ಚರಿಕೆ - ಪರಿಸ್ಥಿತಿ ಪರಿಶೀಲಿಸಿ',
    dangerGo: 'ಸಮುದ್ರಕ್ಕೆ ಹೋಗಬೇಡಿ - ಅಪಾಯ',
    wind: 'ಗಾಳಿಯ ವೇಗ',
    windDir: 'ಗಾಳಿಯ ದಿಕ್ಕು',
    waves: 'ಅಲೆಗಳ ಎತ್ತರ',
    tides: 'ಉಬ್ಬರವಿಳಿತದ ವೇಳಾಪಟ್ಟಿ',
    highTide: 'ಭರತ (High)',
    lowTide: 'ಇಳಿತ (Low)',
    sunrise: 'ಸೂರ್ಯೋದಯ',
    sunset: 'ಸೂರ್ಯಾಸ್ತ',
    humidity: 'ಆರ್ದ್ರತೆ',
    rainChance: 'ಮಳೆಯ ಸಾಧ್ಯತೆ',
    knots: 'ನಾಟ್ಸ್',
    meters: 'ಮೀಟರ್',
    tempRange: 'ತಾಪಮಾನ ಶ್ರೇಣಿ',
    weatherTitle: 'ಇಂದಿನ ಹವಾಮಾನ',
    forecastTitle: '೫-೭ ದಿನಗಳ ಸಮುದ್ರ ಮುನ್ಸೂಚನೆ',
    mapTitle: 'ಮೀನುಗಾರಿಕಾ ವಲಯಗಳ ನಕ್ಷೆ',
    zonesLegend: 'ಸೂಚನೆ: ಹಸಿರು = ಸುರಕ್ಷಿತ, ಕಿತ್ತಳೆ = ಎಚ್ಚರಿಕೆ, ಕೆಂಪು = ಅಪಾಯ',
    catchReports: 'ಮೀನುಗಾರಿಕೆ ದಾಖಲೆಗಳು',
    marketPrices: 'ಮಾರುಕಟ್ಟೆ ದರಗಳು',
    postCatch: 'ದಾಖಲೆ ಸೇರಿಸಿ',
    postPrice: 'ದರ ನವೀಕರಿಸಿ',
    fishType: 'ಮೀನಿನ ವಿಧ',
    quantity: 'ಪ್ರಮಾಣ (ಕೆ.ಜಿ)',
    location: 'ಬಂದರು ಸ್ಥಳ',
    postBtn: 'ಸಲ್ಲಿಸಿ',
    pricePerKg: 'ಪ್ರತಿ ಕೆ.ಜಿ ಬೆಲೆ',
    postedBy: 'ವರದಿ ಮಾಡಿದವರು',
    activeAlerts: 'ಸಕ್ರಿಯ ಎಚ್ಚರಿಕೆಗಳು',
    emergencyContacts: 'ಕರಾವಳಿ ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    shareLocation: 'ವಾಟ್ಸಾಪ್ ಮೂಲಕ ಸ್ಥಳ ಹಂಚಿಕೊಳ್ಳಿ',
    sosTitle: 'ತುರ್ತು ಸಹಾಯ (SOS)',
    sosInstructions: 'ನಿಮ್ಮ ನಿಖರವಾದ ಜಿಪಿಎಸ್ ಸ್ಥಳವನ್ನು ಕುಟುಂಬದೊಂದಿಗೆ ಮತ್ತು ಕೋಸ್ಟ್ ಗಾರ್ಡ್ ಜೊತೆಗೆ ಹಂಚಿಕೊಳ್ಳಲು ಕೆಳಗೆ ಟ್ಯಾಪ್ ಮಾಡಿ.',
    coordinates: 'ನಿಮ್ಮ ಜಿಪಿಎಸ್ ಸ್ಥಳ',
    fetchingCoords: 'ಜಿಪಿಎಸ್ ಸ್ಥಳ ಪಡೆಯಲಾಗುತ್ತಿದೆ...',
    gpsError: 'ಜಿಪಿಎಸ್ ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ಬಂದರಿನ ಹೆಸರನ್ನು ಹಂಚಿಕೊಳ್ಳಿ.',
    adminTitle: 'ಮೀನುಗಾರಿಕೆ ಅಧಿಕಾರಿ ನಿಯಂತ್ರಣ',
    adminPassword: 'ಪಾಸ್ವರ್ಡ್ ನಮೂದಿಸಿ',
    adminSubmit: 'ಲಾಗಿನ್',
    adminLogout: 'ಲಾಗಿನ್ ಅಂತ್ಯ',
    postAlertTitle: 'ಹೊಸ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಪ್ರಕಟಿಸಿ',
    alertTitle: 'ಎಚ್ಚರಿಕೆಯ ಶೀರ್ಷಿಕೆ',
    alertBody: 'ಎಚ್ಚರಿಕೆಯ ವಿವರ',
    alertSeverity: 'ಅಪಾಯದ ಮಟ್ಟ',
    alertExpiry: 'ಅವಧಿ ಮುಗಿಯುವ ಸಮಯ (ಗಂಟೆಗಳಲ್ಲಿ)',
    info: 'ಮಾಹಿತಿ ಪ್ರಕಟಣೆ',
    warning: 'ಎಚ್ಚರಿಕೆ ಪ್ರಕಟಣೆ',
    danger: 'ಅಪಾಯದ ಬಿರುಗಾಳಿ ಎಚ್ಚರಿಕೆ',
    moderateCatches: 'ವರದಿಗಳ ನಿರ್ವಹಣೆ',
    priceTrend: 'ಮೀನಿನ ಮಾರುಕಟ್ಟೆ ದರ ಪಟ್ಟಿ',
    addPriceSuccess: 'ಮಾರುಕಟ್ಟೆ ದರ ನವೀಕರಿಸಲಾಗಿದೆ!',
    addCatchSuccess: 'ದಾಖಲೆ ಯಶಸ್ವಿಯಾಗಿ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ!',
    addAlertSuccess: 'ಹೊಸ ಎಚ್ಚರಿಕೆ ಪ್ರಕಟಿಸಲಾಗಿದೆ!',
    deleteBtn: 'ಅಳಿಸಿ',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...'
  },
  ta: {
    appName: 'தீரா கனெக்ட் (TeeraConnect)',
    tagline: 'கடலோர வானிலை மற்றும் மீனவர் சமூகம்',
    home: 'முகப்பு',
    forecast: 'வானிலை முன்னறிவிப்பு',
    map: 'வரைபடம்',
    community: 'சமூகம்',
    sos: 'அவசர உதவி',
    admin: 'நிர்வாகி',
    lastUpdated: 'கடைசியாக புதுப்பிக்கப்பட்டது',
    simulatedData: 'விவகார உருவகப்படுத்தப்பட்ட தரவு',
    realTimeData: 'நிகழ்நேர தரவு',
    refresh: 'புதுப்பி',
    selectLocation: 'துறைமுகத்தை தேர்வு செய்க',
    safetyStatus: 'பாதுகாப்பு நிலை',
    safeToGo: 'கடலுக்குச் செல்ல பாதுகாப்பானது',
    cautionGo: 'எச்சரிக்கை - நிலைமைகளை சரிபார்க்கவும்',
    dangerGo: 'கடலுக்கு செல்ல வேண்டாம் - ஆபத்து',
    wind: 'காற்றின் வேகம்',
    windDir: 'காற்றின் திசை',
    waves: 'அலை உயரம்',
    tides: 'அலை அட்டவணை',
    highTide: 'நெடுவலை (High)',
    lowTide: 'குறுவலை (Low)',
    sunrise: 'சூரிய உதயம்',
    sunset: 'சூரிய அஸ்தமனம்',
    humidity: 'ஈரப்பதம்',
    rainChance: 'மழை வாய்ப்பு',
    knots: 'நாட்ஸ்',
    meters: 'மீட்டர்',
    tempRange: 'வெப்பநிலை வரம்பு',
    weatherTitle: 'இன்றைய வானிலை',
    forecastTitle: '5-7 நாள் கடல் முன்னறிவிப்பு',
    mapTitle: 'மீன்பிடி மண்டல வரைபடம்',
    zonesLegend: 'குறியீடு: பச்சை = பாதுகாப்பானது, ஆரஞ்சு = எச்சரிக்கை, சிவப்பு = ஆபத்து',
    catchReports: 'மீன்பிடி பதிவுகள்',
    marketPrices: 'சந்தை விலைகள்',
    postCatch: 'பதிவை சேர்',
    postPrice: 'விலையை புதுப்பி',
    fishType: 'மீன் வகை',
    quantity: 'அளவு (கிலோ)',
    location: 'துறைமுக இருப்பிடம்',
    postBtn: 'சமர்ப்பி',
    pricePerKg: 'ஒரு கிலோ விலை',
    postedBy: 'பதிவிட்டவர்',
    activeAlerts: 'செயலில் உள்ள எச்சரிக்கைகள்',
    emergencyContacts: 'கடலோர அவசர தொடர்புகள்',
    shareLocation: 'வாட்ஸ்அப் மூலம் இருப்பிடத்தைப் பகிரவும்',
    sosTitle: 'அவசர உதவி (SOS)',
    sosInstructions: 'உங்களது துல்லியமான ஜிபிஎஸ் இருப்பிடத்தை குடும்பத்தினருடனும், கடலோர காவல்படையினருடனும் பகிர கீழே தட்டவும்.',
    coordinates: 'உங்கள் ஜிபிஎஸ் இருப்பிடம்',
    fetchingCoords: 'இருப்பிடம் பெறப்படுகிறது...',
    gpsError: 'ஜிபிஎஸ் இருப்பிடம் கிடைக்கவில்லை. துறைமுக பெயரை பகிரவும்.',
    adminTitle: 'மீன்வளத்துறை அதிகாரி பலகை',
    adminPassword: 'கடவுச்சொல்லை உள்ளிடவும்',
    adminSubmit: 'உள்நுழைய',
    adminLogout: 'வெளியேறு',
    postAlertTitle: 'புதிய கடல்சார் எச்சரிக்கை வெளியிடவும்',
    alertTitle: 'எச்சரிக்கை தலைப்பு',
    alertBody: 'எச்சரிக்கை விவரங்கள்',
    alertSeverity: 'ஆபத்து நிலை',
    alertExpiry: 'காலாவதி நேரம் (மணிநேரம்)',
    info: 'தகவல் அறிவிப்பு',
    warning: 'எச்சரிக்கை அறிவிப்பு',
    danger: 'ஆபத்தான புயல் எச்சரிக்கை',
    moderateCatches: 'பதிவுகள் மேலாண்மை',
    priceTrend: 'மீன் சந்தை விலை பட்டியல்',
    addPriceSuccess: 'சந்தை விலை புதுப்பிக்கப்பட்டது!',
    addCatchSuccess: 'மீன்பிடி பதிவு பகிரப்பட்டது!',
    addAlertSuccess: 'புதிய எச்சரிக்கை வெளியிடப்பட்டது!',
    deleteBtn: 'நீக்கு',
    loading: 'ஏற்றப்படுகிறது...'
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState('en');

  const t = (key) => {
    return translations[lang][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
